import Head from "next/head";
import {   useMemo, useState } from "react";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Resume from "../components/Resume";
import Services from "../components/Services";
import SocialMedia from "../components/SocialMedia";
import { UserContext } from "../Context/UserContext";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const providerStates = useMemo(() => ({darkMode, setDarkMode}), [darkMode, setDarkMode])
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>EL MHERZI YASSINE Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 bg-white dark:bg-gray-900 md:px-20 lg:px-40 ">
        <section className="min-h-screen">
          <UserContext.Provider value={providerStates}>
            <Navbar  />
            <Resume />
            <SocialMedia />
            <Services />
            <Projects />
          </UserContext.Provider>
        </section>
      </main>
    </div>
  );
}
